/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTrackingRouteImport } from './routes/app.tracking'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRoutesRouteImport } from './routes/app.routes'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppParentRouteImport } from './routes/app.parent'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppEmergencyRouteImport } from './routes/app.emergency'
import { Route as AppDriversRouteImport } from './routes/app.drivers'
import { Route as AppDriverRouteImport } from './routes/app.driver'
import { Route as AppBusesRouteImport } from './routes/app.buses'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAdminRouteImport } from './routes/app.admin'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrackingRoute = AppTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesRoute = AppRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppParentRoute = AppParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppEmergencyRoute = AppEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversRoute = AppDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppRoute,
} as any)
const AppDriverRoute = AppDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AppRoute,
} as any)
const AppBusesRoute = AppBusesRouteImport.update({
  id: '/buses',
  path: '/buses',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/buses': typeof AppBusesRoute
  '/app/driver': typeof AppDriverRoute
  '/app/drivers': typeof AppDriversRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/parent': typeof AppParentRoute
  '/app/reports': typeof AppReportsRoute
  '/app/routes': typeof AppRoutesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/tracking': typeof AppTrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/buses': typeof AppBusesRoute
  '/app/driver': typeof AppDriverRoute
  '/app/drivers': typeof AppDriversRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/parent': typeof AppParentRoute
  '/app/reports': typeof AppReportsRoute
  '/app/routes': typeof AppRoutesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/tracking': typeof AppTrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/buses': typeof AppBusesRoute
  '/app/driver': typeof AppDriverRoute
  '/app/drivers': typeof AppDriversRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/parent': typeof AppParentRoute
  '/app/reports': typeof AppReportsRoute
  '/app/routes': typeof AppRoutesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/tracking': typeof AppTrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/downloads'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/app/admin'
    | '/app/analytics'
    | '/app/buses'
    | '/app/driver'
    | '/app/drivers'
    | '/app/emergency'
    | '/app/notifications'
    | '/app/parent'
    | '/app/reports'
    | '/app/routes'
    | '/app/settings'
    | '/app/students'
    | '/app/tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/downloads'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/app/admin'
    | '/app/analytics'
    | '/app/buses'
    | '/app/driver'
    | '/app/drivers'
    | '/app/emergency'
    | '/app/notifications'
    | '/app/parent'
    | '/app/reports'
    | '/app/routes'
    | '/app/settings'
    | '/app/students'
    | '/app/tracking'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/downloads'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/app/admin'
    | '/app/analytics'
    | '/app/buses'
    | '/app/driver'
    | '/app/drivers'
    | '/app/emergency'
    | '/app/notifications'
    | '/app/parent'
    | '/app/reports'
    | '/app/routes'
    | '/app/settings'
    | '/app/students'
    | '/app/tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tracking': {
      id: '/app/tracking'
      path: '/tracking'
      fullPath: '/app/tracking'
      preLoaderRoute: typeof AppTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/routes': {
      id: '/app/routes'
      path: '/routes'
      fullPath: '/app/routes'
      preLoaderRoute: typeof AppRoutesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parent': {
      id: '/app/parent'
      path: '/parent'
      fullPath: '/app/parent'
      preLoaderRoute: typeof AppParentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/emergency': {
      id: '/app/emergency'
      path: '/emergency'
      fullPath: '/app/emergency'
      preLoaderRoute: typeof AppEmergencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/drivers': {
      id: '/app/drivers'
      path: '/drivers'
      fullPath: '/app/drivers'
      preLoaderRoute: typeof AppDriversRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/driver': {
      id: '/app/driver'
      path: '/driver'
      fullPath: '/app/driver'
      preLoaderRoute: typeof AppDriverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buses': {
      id: '/app/buses'
      path: '/buses'
      fullPath: '/app/buses'
      preLoaderRoute: typeof AppBusesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBusesRoute: typeof AppBusesRoute
  AppDriverRoute: typeof AppDriverRoute
  AppDriversRoute: typeof AppDriversRoute
  AppEmergencyRoute: typeof AppEmergencyRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppParentRoute: typeof AppParentRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRoutesRoute: typeof AppRoutesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppTrackingRoute: typeof AppTrackingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBusesRoute: AppBusesRoute,
  AppDriverRoute: AppDriverRoute,
  AppDriversRoute: AppDriversRoute,
  AppEmergencyRoute: AppEmergencyRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppParentRoute: AppParentRoute,
  AppReportsRoute: AppReportsRoute,
  AppRoutesRoute: AppRoutesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppTrackingRoute: AppTrackingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
